KunstmaanMediaBundle_pagepartadmin:
    resource: "@KunstmaanPagePartBundle/Controller/PagePartAdminController.php"
    type:     annotation
    prefix:   /admin

KunstmaanMediaBundle_ajaxpagepart:
    resource: "@KunstmaanPagePartBundle/Controller/AjaxPagePartController.php"
    type:     annotation
    prefix:   /admin

